# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Marino Melchiori
#Lyanon
tagline:             '@m_melchio'
#'A Jekyll theme'
description:         'Marino Melchioris Blog. Twitter: <a href="https://twitter.com/m_melchio" target="_blank">@m_melchio</a>.'
url:                 http://lanyon.getpoole.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
