# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Marino Melchiori
#Lyanon
tagline:             '@m_melchio'
#'A Jekyll theme'
description:         'Marino Melchioris Blog. Twitter: <a href="https://twitter.com/m_melchio" target="_blank">@m_melchio</a>.'
paginate:            5

# About/contact
author:
  name:              Marino Melchiori
  url:               https://twitter.com/m_melchio
  email:             marino.melchiori@gmail.com

# Custom vars
version:             1.0.0
